
if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  if [ "${BUILD_WITH_SERIALIZATION_WO_PYTHON}" = "true" ]; then
    cmake -DWITH_SERIALIZATION=ON -DWITH_PYTHON=OFF -DEIGEN3_INCLUDE_DIR=`pwd`/eigen-eigen-bdd17ee3b1b3/ ..
  else
    cmake -DWITH_SERIALIZATION=OFF -DWITH_PYTHON=ON -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} -DPYTHON_LIBRARY=${PYTHON_LIBRARY} -DEIGEN3_INCLUDE_DIR=`pwd`/eigen-eigen-bdd17ee3b1b3/ ..
  fi
fi
if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
  cmake -DWITH_SERIALIZATION=OFF -DWITH_PYTHON=ON -DEIGEN3_INCLUDE_DIR=`pwd`/eigen-eigen-bdd17ee3b1b3/ ..
fi
